var VALID_LINE_LENGTH=115,DATE_START_IDX=13,LAT_START_IDX=81,LAT_LENGTH=4,LONG_START_IDX=87,LONG_LENGTH=5,DATE_STRING_LENGTH=21,ECLIPSE_TYPE_IDX=56,CALC_ITERATIONS=50;function PositionObj(l,k,u){this.altitude=this.longitude=this.latitude=0;this.setPosition=function(k,z,h){"number"===typeof k&&(this.latitude=k);"number"===typeof z&&(this.longitude=z);"number"===typeof h&&(this.altitude=h)};this.setPosition(l,k,u)}
function PositionLimits(){var l=0,k=0,u=0,r=0;this.setEastLimit=function(k){"number"===typeof k&&180>=k&&-180<=k&&(l=k)};this.setWestLimit=function(r){"number"===typeof r&&180>=r&&-180<=r&&(k=r)};this.setNorthLimit=function(k){"number"===typeof k&&90>=k&&-90<=k&&(r=k)};this.setSouthLimit=function(k){"number"===typeof k&&90>=k&&-90<=k&&(u=k)};this.getNorthLimit=function(){return r};this.getSouthLimit=function(){return u};this.getWestLimit=function(){return k};this.getEastLimit=function(){return l}}
function CircumstanceDates(l){this.c4Date=this.c3Date=this.midDate=this.c2Date=this.c1Date=null;l&&(this.c1Date=l.c1Date,this.c2Date=l.c2Date,this.midDate=l.midDate,this.c3Date=l.c3Date,this.c4Date=l.c4Date);this.setC1Date=function(k){this.c1Date=k};this.setC2Date=function(k){this.c2Date=k};this.setMidDate=function(k){this.midDate=k};this.setC3Date=function(k){this.c3Date=k};this.setC4Date=function(k){this.c4Date=k};this.getC1Date=function(){return this.c1Date};this.getC2Date=function(){return this.c2Date};
this.getMidDate=function(){return this.midDate};this.getC3Date=function(){return this.c3Date};this.getC4Date=function(){return this.c4Date}}
function TimeSpan(l,k){var u=0,r=0,z=0,h=0,A=0,B=0;this.setSpan=function(a,d){u="undefined"===typeof d&&"undefined"===typeof a?0:"number"===typeof d&&"number"===typeof a?d-a:"undefined"===typeof d&&"number"===typeof a?a:"undefined"===typeof d.getTime&&"function"===typeof a.getTime?a.getTime():"function"===typeof d.getTime&&"function"===typeof a.getTime?d.getTime()-a.getTime():0;B=Math.abs(u/864E5);A=1<=B?24*(B-Math.floor(B)):24*B;h=1<=A?60*(A-Math.floor(A)):60*A;z=1<=h?60*(h-Math.floor(h)):60*h;r=
1<=z?Math.round(1E3*(z-Math.floor(z))):Math.round(1E3*z);return u};this.getRawMilliSeconds=function(){return u};this.checkNegative=function(){return 0>u?!0:!1};this.getDays=function(){return Math.floor(B)};this.getHours=function(){return Math.floor(A)};this.getMinutes=function(){return Math.floor(h)};this.getSeconds=function(){return Math.floor(z)};this.getMilliseconds=function(){return r};this.toTimeString=function(){var a="",d=Math.floor(this.getDays()),b=Math.floor(this.getHours()),e=Math.floor(this.getMinutes()),
c=Math.floor(this.getSeconds());this.checkNegative()&&(a+="-");0<d&&(a+=d+":");10<=b&&(a+=""+b+":");0<b&&10>b&&(a+="0"+b+":");0===b&&0<d&&(a+="00:");10<=e&&(a+=""+e+":");10>e&&0<e&&(a+="0"+e+":");0===e&&(a+="00:");10<=c&&(a+=""+c);0<c&&10>c&&(a+="0"+c);0===c&&(a+="00");return a};return this.setSpan(l,k)}TimeSpan.prototype.toString=function(){return""+this.getRawMilliSeconds()};TimeSpan.prototype.toJSON=function(){return this.getRawMilliSeconds()};
function julianDayToTime(l){l*=864E5;var k=new Date(Date.UTC(-4713,0,1,12,0,0,0)),u=k.getTime();k.setTime(u+l+282528E5);return k}
function ObserverConstants(l,k,u){this.latRadians=l*Math.PI/180;this.longRadians=-1*k*Math.PI/180;this.altitude=u;this.timeZone=0;this.getAltitude=function(){return this.altitude};this.getLatRadians=function(){return this.latRadians};this.getLongRadians=function(){return this.longRadians};this.getTimeZone=function(){return this.timeZone};l=Math.atan(.99664719*Math.tan(this.getLatRadians()));this.rhoSinO=.99664719*Math.sin(l)+this.getAltitude()/6378140*Math.sin(this.getLatRadians());this.rhoCosO=Math.cos(l)+
this.getAltitude()/6378140*Math.cos(this.getLatRadians());this.getRhoSinO=function(){return this.rhoSinO};this.getRhoCosO=function(){return this.rhoCosO}}
function EclipseCircumstances(){this.eventType=new Number;this.t=new Number;this.x=new Number;this.y=new Number;this.d=new Number;this.sinDelta=new Number;this.cosDelta=new Number;this.mu=new Number;this.l1=new Number;this.l2=new Number;this.dx=new Number;this.dy=new Number;this.dd=new Number;this.dmu=new Number;this.dl1=new Number;this.dl2=new Number;this.h=new Number;this.sinH=new Number;this.cosH=new Number;this.xi=new Number;this.eta=new Number;this.zeta=new Number;this.dxi=new Number;this.deta=
new Number;this.u=new Number;this.vLoc=new Number;this.a=new Number;this.b=new Number;this.l1prime=new Number;this.l2prime=new Number;this.nSquared=new Number;this.p=new Number;this.alt=new Number;this.q=new Number;this.vObs=new Number;this.azi=new Number;this.mid=new Number;this.magnitude=new Number;this.moonSun=new Number;this.localType=new Number}
function ObserverCircumstances(l){this.isVisible=!1;this.eclipseType="None";this.pAngle=this.depth=this.coverage=this.magnitude=0;this.northOfCenter=!0;this.c4Altitude=this.c1Altitude=this.midAltitude=0;this.circDates=new CircumstanceDates;this.fourthContactBelowHorizon=this.thirdContactBelowHorizon=this.midEclipseBelowHorizon=this.secondContactBelowHorizon=this.firstContactBelowHorizon=!1;this.c1c4TimeSpan=new TimeSpan;this.c2c3TimeSpan=new TimeSpan;this.set=function(k){"object"===typeof k&&null!==
k&&(this.isVisible=k.isVisible,this.eclipseType=k.eclipseType,this.magnitude=k.magnitude,this.coverage=k.coverage,this.depth=k.depth,this.pAngle=k.pAngle,this.northOfCenter=k.northOfCenter,this.midAltitude=k.midAltitude,this.c1Altitude=k.c1Altitude,this.c4Altitude=k.c4Altitude,this.circDates=new CircumstanceDates(k.circDates),this.firstContactBelowHorizon=k.firstContactBelowHorizon,this.secondContactBelowHorizon=k.secondContactBelowHorizon,this.midEclipseBelowHorizon=k.midEclipseBelowHorizon,this.thirdContactBelowHorizon=
k.thirdContactBelowHorizon,this.fourthContactBelowHorizon=k.fourthContactBelowHorizon,this.c1c4TimeSpan=new TimeSpan(k.c1c4TimeSpan),this.c2c3TimeSpan=new TimeSpan(k.c2c3TimeSpan))};this.set(l)}
function Besselian(){this.julianDayMax=new Number;this.t0=new Number;this.tMin=new Number;this.tMax=new Number;this.dUTC=new Number;this.dT=new Number;this.x0=new Number;this.x1=new Number;this.x2=new Number;this.x3=new Number;this.y0=new Number;this.y1=new Number;this.y2=new Number;this.y3=new Number;this.d0=new Number;this.d1=new Number;this.d2=new Number;this.m0=new Number;this.m1=new Number;this.m2=new Number;this.l10=new Number;this.l11=new Number;this.l12=new Number;this.l20=new Number;this.l21=
new Number;this.l22=new Number;this.tanF1=new Number;this.tanF2=new Number}
function EclipseData(l){function k(a){a=Math.abs(a);return 90>a?.1*Math.cos(Math.PI*a/180):1E-9}function u(a,d){if(0<a&&0<d||0>a&&0>d){var b=a-d;0>b&&(b+=360);return b}return 0<a?a+Math.abs(d):180-Math.abs(a)+180-Math.abs(d)}function r(a,d){var b=a+d;180<b&&(b-=360);-180>b&&(b+=360);return b}function z(a,d){var b=a+d;90<b&&(b=90);-90>b&&(b=-90);return b}function h(a,d){var b=u(a,d);return 180>b&&0<b?!0:!1}function A(a,d){return a.longitude===d.longitude?0:h(a.longitude,d.longitude)?1:-1}function B(a,
d){return a.longitude===d.longitude?0:h(a.longitude,d.longitude)?-1:1}this.type="";this.maxEclipseDate=new Date;this.midEclipsePoint=new PositionObj;this.besselianElements=new Besselian;this.observerConstants=null;this.c1Circumstances=new EclipseCircumstances;this.c2Circumstances=new EclipseCircumstances;this.midCircumstances=new EclipseCircumstances;this.c3Circumstances=new EclipseCircumstances;this.c4Circumstances=new EclipseCircumstances;this.eastPenumbraLineTimes=this.westPenumbraLineTimes=this.northUmbraLineTimes=
this.southUmbraLineTimes=this.centralLineTimes=this.eastLimitLine=this.westLimitLine=this.northUmbraLine=this.southUmbraLine=this.centralLine=this.southPenumbraLine=this.northPenumbraLine=null;this.toDate=function(a){if(a){var d=Math.floor(a),b=24*(a-d);a=Math.floor((d-122.1)/365.25);var e=Math.floor(365.25*a),c=Math.floor((d-e)/30.6001),e=d-e-Math.floor(30.6001*c),c=13.5>c?c-1:c-13;a=2.5<c?a-4716:a-4715;c--;var d=Math.floor(b),b=60*b-60*d,x=60*b-60*Math.floor(b),g=Math.round(1E3*(x-Math.floor(x))),
b=Math.floor(b),x=Math.floor(x);return new Date(Date.UTC(a,c,e,d,b,x,g))}return null};this.destroy=function(){this.observerConstants=null;this.c1Circumstances=new EclipseCircumstances;this.c2Circumstances=new EclipseCircumstances;this.midCircumstances=new EclipseCircumstances;this.c3Circumstances=new EclipseCircumstances;this.c4Circumstances=new EclipseCircumstances;this.eastPenumbraLineTimes=this.westPenumbraLineTimes=this.northUmbraLineTimes=this.southUmbraLineTimes=this.centralLineTimes=this.eastLimitLine=
this.westLimitLine=this.northUmbraLine=this.southUmbraLine=this.centralLine=this.southPenumbraLine=this.northPenumbraLine=null};this.deepCopyLineTimes=function(a){var d=[];if("object"===typeof a&&null!==a)for(var b=0;b<a.length;b++)d.push(new CircumstanceDates(a[b]));return d};this.set=function(a){"object"===typeof a&&null!==a&&(this.type=a.type,this.maxEclipseDate=new Date(a.maxEclipseDate),this.midEclipsePoint=a.midEclipsePoint,this.besselianElements=a.besselianElements,this.observerConstants=a.observerConstants,
this.c1Circumstances=a.c1Circumstances,this.c2Circumstances=a.c2Circumstances,this.midCircumstances=a.midCircumstances,this.c3Circumstances=a.c3Circumstances,this.c4Circumstances=a.c4Circumstances,this.northPenumbraLine=a.northPenumbraLine,this.southPenumbraLine=a.southPenumbraLine,this.centralLine=a.centralLine,this.southUmbraLine=a.southUmbraLine,this.northUmbraLine=a.northUmbraLine,this.westLimitLine=a.westLimitLine,this.eastLimitLine=a.eastLimitLine,this.centralLineTimes=this.deepCopyLineTimes(a.centralLineTimes),
this.southUmbraLineTimes=this.deepCopyLineTimes(a.southUmbraLineTimes),this.northUmbraLineTimes=this.deepCopyLineTimes(a.northUmbraLineTimes),this.westPenumbraLineTimes=this.deepCopyLineTimes(a.westPenumbraLineTimes),this.eastPenumbraLineTimes=this.deepCopyLineTimes(a.eastPenumbraLineTimes))};this.calculateLocalCircumstances=function(a,d,b){if("number"===typeof a&&"number"===typeof d){var e=0;var c=new ObserverCircumstances;b&&(isNaN(b)||(e=b));this.observerConstants=new ObserverConstants(a,d,e);
this.getAll();c.magnitude=100*this.midCircumstances.magnitude;c.northOfCenter=0>this.midCircumstances.vLoc;c.midAltitude=this.getAlt(this.midCircumstances);c.c1Altitude=this.getAlt(this.c1Circumstances);c.c4Altitude=this.getAlt(this.c4Circumstances);c.circDates.setC1Date(this.getDate(this.c1Circumstances));c.circDates.setMidDate(this.getDate(this.midCircumstances));c.circDates.setC4Date(this.getDate(this.c4Circumstances));c.circDates.setC2Date(this.getDate(this.c2Circumstances));c.circDates.setC3Date(this.getDate(this.c3Circumstances));
c.coverage=this.getCoverage();c.depth=this.getDepth();c.pAngle=this.getP(this.midCircumstances);if(0<this.midCircumstances.localType&&this.checkHorizons(c))switch(c.isVisible=!0,null!==c.circDates.getC1Date()&&null!==c.circDates.getC4Date()&&c.c1c4TimeSpan.setSpan(this.toDate(c.circDates.getC1Date()),this.toDate(c.circDates.getC4Date())),this.midCircumstances.localType){case 1:c.eclipseType="Partial";break;case 2:c.eclipseType="Annular";null!==c.circDates.getC2Date()&&null!==c.circDates.getC3Date()&&
c.c2c3TimeSpan.setSpan(this.toDate(c.circDates.getC2Date()),this.toDate(c.circDates.getC3Date()));break;case 3:c.eclipseType="Total";null!==c.circDates.getC2Date()&&null!==c.circDates.getC3Date()&&c.c2c3TimeSpan.setSpan(this.toDate(c.circDates.getC2Date()),this.toDate(c.circDates.getC3Date()));break;default:c.eclipseType="None"}}else throw"Pleae input proper latitude and longitude to calclulate local cirucumstances.";return c};this.checkHorizons=function(a){0>this.getAlt(this.c1Circumstances)?a.firstContactBelowHorizon=
!0:a.firstContactBelowHorizon=!1;0>this.getAlt(this.midCircumstances)?a.midEclipseBelowHorizon=!0:a.midEclipseBelowHorizon=!1;0>this.getAlt(this.c4Circumstances)?a.fourthContactBelowHorizon=!0:a.fourthContactBelowHorizon=!1;0>this.getAlt(this.c2Circumstances)?a.secondContactBelowHorizon=!0:a.secondContactBelowHorizon=!1;0>this.getAlt(this.c3Circumstances)?a.thirdContactBelowHorizon=!0:a.thirdContactBelowHorizon=!1;if(1===this.midCircumstances.localType){if(a.fourthContactBelowHorizon&&a.midEclipseBelowHorizon&&
a.firstContactBelowHorizon)return this.midCircumstances.localType=0,!1}else{if(a.fourthContactBelowHorizon&&a.midEclipseBelowHorizon&&a.firstContactBelowHorizon&&a.secondContactBelowHorizon&&a.thirdContactBelowHorizon)return this.midCircumstances.localType=0,!1;a.secondContactBelowHorizon&&a.thirdContactBelowHorizon&&(this.midCircumstances.localType=1)}return!0};this.checkCentralHorizons=function(a,d){return!a.isVisible||a.midEclipseBelowHorizon?!0:!1};this.checkPartialHorizons=function(a,d){return a.firstContactBelowHorizon&&
d||a.fourthContactBelowHorizon&&!d?!0:!1};this.getCentralLine=function(){return this.centralLine};this.setCentralLine=function(a){this.centralLine=a};this.setCentralLineTimes=function(a){this.centralLineTimes=this.deepCopyLineTimes(a)};this.getCentralLineTimes=function(){return this.centralLineTimes};this.drawCentralLine=function(){if(null!==this.centralLine)return this.centralLine;if("Annular"===this.type||"Total"===this.type||"Hybrid"===this.type){this.centralLine=[];this.centralLineTimes=[];this.centralLine.push(this.midEclipsePoint);
var a;k(this.midEclipsePoint.latitude);var d=.1,b=0;new ObserverCircumstances;var e=this.calculateLocalCircumstances(this.midEclipsePoint.latitude,this.midEclipsePoint.longitude,0);this.centralLineTimes.push(e.circDates);for(var c=1;-2<c;c-=2){var x=!1;for(var g=a=k(b)*c;180>=Math.abs(g);g+=a){a=k(b)*c;var p=r(this.midEclipsePoint.longitude,g);g===a&&(b=this.midEclipsePoint.latitude);e=this.calculateLocalCircumstances(b,p,0);var f=e.depth;if(this.checkCentralHorizons(e,1===c)||x)break;if(99.9>e.depth){var h=
e.northOfCenter?-1:1;d=Math.abs(d)*h;for(b+=d;90>=Math.abs(b);b+=d)if(e=this.calculateLocalCircumstances(b,p,0),this.checkCentralHorizons(e,1===c)&&(x=!0),99.9>e.depth){if(e.northOfCenter&&1===h||!e.northOfCenter&&-1===h){b-=(100-e.depth)/(100-f+(100-e.depth))*d;e=this.calculateLocalCircumstances(b,p,0);1===c?(this.centralLine.push(new PositionObj(b,p)),this.centralLineTimes.push(e.circDates)):(this.centralLine.unshift(new PositionObj(b,p)),this.centralLineTimes.unshift(e.circDates));break}f=e.depth}else{e=
this.calculateLocalCircumstances(b,p,0);1===c?this.centralLine.push(new PositionObj(b,p)):this.centralLine.unshift(new PositionObj(b,p));this.centralLineTimes.unshift(e.circDates);break}}else e=this.calculateLocalCircumstances(b,p,0),1===c?(this.centralLine.push(new PositionObj(b,p)),this.centralLineTimes.push(e.circDates)):(this.centralLine.unshift(new PositionObj(b,p)),this.centralLineTimes.unshift(e.circDates))}}}return this.centralLine};this.getPenumbraStartTimeJD=function(){var a=null;this.westPenumbraLineTimes&&
(a=[],a=a.concat(this.westPenumbraLineTimes),a=a.sort(function(a,b){return null!==a.getMidDate()&&null!==b.getMidDate()?a.getMidDate()-b.getMidDate():0}),a=a[0].getMidDate(),a-=.03);return a};this.getPenumbraStartTime=function(){return this.toDate(this.getPenumbraStartTimeJD())};this.getPenumbraEndTimeJD=function(){var a=null;this.eastPenumbraLineTimes&&(a=[],a=a.concat(this.eastPenumbraLineTimes),a=a.sort(function(a,b){return null!==b.getMidDate()&&null!==a.getMidDate()?b.getMidDate()-a.getMidDate():
0}),a=a[0].getMidDate(),a+=.03);return a};this.getPenumbraEndTime=function(){return this.toDate(this.getPenumbraEndTimeJD())};this.getUmbraStartTimeJD=function(){var a=null;this.centralLineTimes?a=this.centralLineTimes[0].getC2Date():(this.northUmbraLineTimes&&(a=this.northUmbraLineTimes[0].getMidDate()),this.southUmbraLineTimes&&(a=this.southUmbraLineTimes[0].getMidDate()));a&&(a-=.001);return a};this.getUmbraStartTime=function(){return this.toDate(this.getUmbraStartTimeJD())};this.getUmbraEndTimeJD=
function(){var a=null;this.centralLineTimes?a=this.centralLineTimes[this.centralLineTimes.length-1].getC3Date():(this.northUmbraLineTimes&&(a=this.northUmbraLineTimes[this.northUmbraLineTimes.length-1].getMidDate()),this.southUmbraLineTimes&&(a=this.southUmbraLineTimes[this.northUmbraLineTimes.length-1].getMidDate()));a&&(a+=.001);return a};this.getUmbraEndTime=function(){return this.toDate(this.getUmbraEndTimeJD())};this.setSouthUmbraLine=function(a){this.southUmbraLine=a};this.getSouthUmbraLine=
function(){return this.southUmbraLine};this.setNorthUmbraLine=function(a){this.northUmbraLine=a};this.getNorthUmbraLine=function(){return this.northUmbraLine};this.getNorthUmbraTimes=function(){return this.northUmbraLineTimes};this.setNorthUmbraTimes=function(a){this.northUmbraLineTimes=this.deepCopyLineTimes(a)};this.getSouthUmbraTimes=function(){return this.southUmbraLineTimes};this.setSouthUmbraTimes=function(a){this.southUmbraLineTimes=this.deepCopyLineTimes(a)};this.drawUmbraLimit=function(a){if(!a&&
this.southUmbraLine)return this.southUmbraLine;if(a&&this.northUmbraLine)return this.northUmbraLine;var d=null,b=null;if("Annular"===this.type||"Total"===this.type||"Hybrid"===this.type){var d=[],b=[];k(this.midEclipsePoint.latitude);var e=.1,c=this.midEclipsePoint.latitude,x=1;new ObserverCircumstances;a||(x=-1);for(var g=1;-1<=g;g-=2){new ObserverCircumstances;var p=100;k(c);c=this.midEclipsePoint.latitude;var f=!1;for(var h=0;180>=Math.abs(h);h+=n){var n=k(c)*g;-1===g&&(h+=n,c=d[0].latitude);var m=
r(this.midEclipsePoint.longitude,h);if(0<h||-1===g){var t=this.calculateLocalCircumstances(c,m,0);p=t.depth;if(this.checkCentralHorizons(t,1===g)||f)break;0>=p&&t.northOfCenter?x=-1:0<p&&t.northOfCenter?x=1:0<p&&!t.northOfCenter?x=-1:0>=p&&!t.northOfCenter&&(x=1)}e=Math.abs(e)*x;for(c+=e;90>=Math.abs(c);c+=e)if(t=this.calculateLocalCircumstances(c,m,0),this.checkCentralHorizons(t,1===g)&&(f=!0),.1<t.depth||-.1>t.depth){if(0>t.depth&&0<p||0<t.depth&&0>p){c-=Math.abs(t.depth)/(Math.abs(p)+Math.abs(t.depth))*
e;t=this.calculateLocalCircumstances(c,m,0);1===g?(d.push(new PositionObj(c,m)),b.push(t.circDates)):(d.unshift(new PositionObj(c,m)),b.unshift(t.circDates));break}p=t.depth}else{t=this.calculateLocalCircumstances(c,m,0);1===g?(d.push(new PositionObj(c,m)),b.push(t.circDates)):(d.unshift(new PositionObj(c,m)),b.unshift(t.circDates));break}}}}b&&0<b.length&&(a?(this.northUmbraLineTimes=[],this.northUmbraLineTimes=this.northUmbraLineTimes.concat(b)):(this.southUmbraLineTimes=[],this.southUmbraLineTimes=
this.southUmbraLineTimes.concat(b)));if(d&&0<d.length){if(a)return this.northUmbraLine=[],this.northUmbraLine=this.northUmbraLine.concat(d);this.southUmbraLine=[];return this.southUmbraLine=this.southUmbraLine.concat(d)}return this.northUmbraLine};this.getNorthPenumbraLine=function(){return this.northPenumbraLine};this.getSouthPenumbraLine=function(){return this.southPenumbraLine};this.setNorthPenumbraLine=function(a){this.northPenumbraLine=a};this.setSouthPenumbraLine=function(a){this.southPenumbraLine=
a};this.drawPenumbralLimit=function(a){if(a&&this.northPenumbralLine)return this.northPenumbraLine;if(!a&&this.southPenumbraLine)return this.southPenumbraLine;var d=[];k(this.midEclipsePoint.latitude);var b=this.midEclipsePoint.longitude,e=this.midEclipsePoint.latitude,c=100,x=1;new ObserverCircumstances;for(var g,p=!0,f=1;-2<f;f-=2){g=!1;var h=k(e)*f;a||(x=-1);if(1===f){var n=.2*x;for(e+=n;90>=Math.abs(e);e+=n){var m=this.calculateLocalCircumstances(e,b,0);if(0<m.magnitude)c=m.magnitude;else{e-=
n*Math.abs(m.magnitude)/(Math.abs(c)+Math.abs(m.magnitude));d.push(new PositionObj(e,b));p=!1;break}}if(p)break}else e=d[0].latitude,b=d[0].longitude;n=.1*x;for(var t=h;180>=Math.abs(t);t+=h){b=r(d[0].longitude,t);m=this.calculateLocalCircumstances(e,b,0);c=m.magnitude;if(this.checkPartialHorizons(m,1===f)||g)break;m.northOfCenter&&0>c?x=-1:!m.northOfCenter&&0>c?x=1:!m.northOfCenter&&0<c?x=-1:m.northOfCenter&&0<c&&(x=1);n=Math.abs(n)*x;p=!0;for(e+=n;90>=Math.abs(e);e+=n){m=this.calculateLocalCircumstances(e,
b,0);this.checkPartialHorizons(m,1===f)&&(g=!0);if(0<c&&0>m.magnitude||0>c&&0<m.magnitude){e-=n*Math.abs(m.magnitude)/(Math.abs(c)+Math.abs(m.magnitude));p=!1;1===f?d.push(new PositionObj(e,b)):d.unshift(new PositionObj(e,b));break}c=m.magnitude}h=k(e)*f}}1>d.length&&(d=null);if(a)return d&&(this.northPenumbraLine=d.slice(1,d.length-1)),this.northPenumbraLine;d&&(this.southPenumbraLine=d.slice(1,d.length-1));return this.southPenumbraLine};this.getWestLimitLine=function(){return this.westLimitLine};
this.getEastLimitLine=function(){return this.eastLimitLine};this.setWestLimitLine=function(a){this.westLimitLine=a};this.setEastLimitLine=function(a){this.eastLimitLine=a};this.getWestLineTimes=function(){return this.westPenumbraLineTimes};this.getPointCount=function(){var a=0;this.getWestLimitLine()&&(a+=this.getWestLimitLine().length);this.getEastLimitLine()&&(a+=this.getEastLimitLine().length);this.getNorthPenumbraLine()&&(a+=this.getNorthPenumbraLine().length);this.getSouthPenumbraLine()&&(a+=
this.getSouthPenumbraLine().length);return a};this.isEclipseOccurring=function(a){try{if(a&&this.getPenumbraEndTime()&&this.getPenumbraStartTime()&&a<=this.getPenumbraEndTime()&&a>=this.getPenumbraStartTime())return!0}catch(d){}return!1};this.setWestLineTimes=function(a){this.westPenumbraLineTimes=this.deepCopyLineTimes(a)};this.getEastLineTimes=function(){return this.eastPenumbraLineTimes};this.setEastLineTimes=function(a){this.eastPenumbraLineTimes=this.deepCopyLineTimes(a)};this.drawEastWestLimit=
function(a){if(a&&this.westLimitLine)return this.westLimitLine;if(!a&&this.eastLimitLine)return this.eastLimitLine;if(!this.southPenumbraLine&&!this.northPenumbraLine)throw"Can't draw east or west limit line without the north and south penumbral limits.";var d=.1;k(0);var b=[],e=!0,c=90,h=0;var g=new ObserverCircumstances;var p=[];if(!this.southPenumbraLine&&this.northPenumbraLine)0<this.northPenumbraLine.length&&(e=!1,c=-89,a?(b.push(this.northPenumbraLine[0]),g=this.calculateLocalCircumstances(this.northPenumbraLine[0].latitude,
this.northPenumbraLine[0].longitude,0)):(b.push(this.northPenumbraLine[this.northPenumbraLine.length-1]),g=this.calculateLocalCircumstances(this.northPenumbraLine[this.northPenumbraLine.length-1].latitude,this.northPenumbraLine[this.northPenumbraLine.length-1].longitude,0)),p.push(g.circDates));else if(0<this.southPenumbraLine.length)if(a)b.push(this.southPenumbraLine[0]),g=this.calculateLocalCircumstances(this.southPenumbraLine[0].latitude,this.southPenumbraLine[0].longitude,0),p.push(g.circDates);
else{b.push(this.southPenumbraLine[this.southPenumbraLine.length-1]);try{g=this.calculateLocalCircumstances(this.southPenumbraLine[this.southPenumbraLine.length-1].latitude,this.southPenumbraLine[this.southPenumbraLine.length-1].longitude,0),p.push(g.circDates)}catch(E){throw"Ummmm no number here!";}}if(a){var f=this.midEclipsePoint.longitude;var D=0<b.length?r(b[0].longitude,-90):r(this.midEclipsePoint.longitude,-90)}else D=this.midEclipsePoint.longitude,f=0<b.length?r(b[0].longitude,90):r(this.midEclipsePoint.longitude,
90);if("Annular"===this.type||"Total"===this.type||"Hybrid"===this.type)c=e?this.northPenumbraLine?a?this.northPenumbraLine[0].latitude:this.northPenumbraLine[this.northPenumbraLine.length-1].latitude:90:this.southPenumbraLine?a?this.southPenumbraLine[0].latitude:this.southPenumbraLine[this.southPenumbraLine.length-1].latitude:-89;e||(d*=-1);if(0<b.length){var n=b[0].latitude;var m=b[0].longitude}else n=0,m=a?r(this.midEclipsePoint.longitude,90):r(this.midEclipsePoint.longitude,-90);var c=Math.abs(c-
n);var t=0<b.length?b[0].latitude:n;for(h+=d;Math.abs(h)<c;h+=d){n=t+h;var v=k(n);g=this.calculateLocalCircumstances(n,m,0);if(a)if(g=g.c4Altitude,0<g){v=-1*Math.abs(v);var l=Math.abs(m-D)}else v=Math.abs(v),l=Math.abs(m-f);else g=g.c1Altitude,0>g?(v=-1*Math.abs(v),l=Math.abs(m-D)):(v=Math.abs(v),l=Math.abs(m-f));180<l&&(l-=180);var u=g;var q=0;var w=m;for(q+=v;Math.abs(q)<=Math.abs(l);q+=v){m=r(w,q);g=this.calculateLocalCircumstances(n,m,0);g=a?g.c4Altitude:g.c1Altitude;if(isNaN(g))break;if(0>g&&
0<u||0<g&&0>u){v=v*Math.abs(g)/(Math.abs(g)+Math.abs(u))*-1;m=r(m,v);b.push(new PositionObj(n,m));g=this.calculateLocalCircumstances(n,m,0);p.push(g.circDates);break}else u=g}}e?!a&&this.northPenumbraLine?(b.push(this.northPenumbraLine[this.northPenumbraLine.length-1]),g=this.calculateLocalCircumstances(b[b.length-1].latitude,b[b.length-1].longitude,0),p.push(g.circDates)):this.northPenumbraLine?(b.push(this.northPenumbraLine[0]),g=this.calculateLocalCircumstances(b[b.length-1].latitude,b[b.length-
1].longitude,0),p.push(g.circDates)):a&&this.eastLimitLine&&(b.push(this.eastLimitLine[this.eastLimitLine.length-1]),g=this.calculateLocalCircumstances(b[b.length-1].latitude,b[b.length-1].longitude,0),p.push(g.circDates)):!a&&this.southPenumbraLine?(b.push(this.southPenumbraLine[this.southPenumbraLine.length-1]),g=this.calculateLocalCircumstances(b[b.length-1].latitude,b[b.length-1].longitude,0),p.push(g.circDates)):this.southPenumbraLine?(b.push(this.southPenumbraLine[0]),g=this.calculateLocalCircumstances(b[b.length-
1].latitude,b[b.length-1].longitude,0),p.push(g.circDates)):a&&this.eastLimitLine&&(b.push(this.eastLimitLine[this.eastLimitLine.length-1]),g=this.calculateLocalCircumstances(b[b.length-1].latitude,b[b.length-1].longitude,0),p.push(g.circDates));b&&1<b.length&&b[0].latitude>b[b.length-1].latitude&&(b=b.reverse(),p=p.reverse());if(a)return console.log("WEST COMPLETE"),this.westLimitLine=[],this.westLimitLine=this.westLimitLine.concat(b),this.westPenumbraLineTimes=[],this.westPenumbraLineTimes=this.westPenumbraLineTimes.concat(p),
this.westLimitLine;this.eastPenumbraLineTimes=[];this.eastPenumbraLineTimes=this.eastPenumbraLineTimes.concat(p);this.eastLimitLine=[];return this.eastLimitLine=this.eastLimitLine.concat(b)};this.getPenumbraLimits=function(){var a=null;if(this.eastLimitLine&&this.westLimitLine&&(this.northPenumbraLine||this.southPenumbraLine)){var d=this.midEclipsePoint.latitude,b=this.midEclipsePoint.latitude,e=this.midEclipsePoint.longitude,c=this.midEclipsePoint.longitude,k=this.midEclipsePoint.longitude,a=new PositionLimits;
this.eastLimitLine[0].latitude>d&&(d=this.eastLimitLine[0].latitude);this.eastLimitLine[this.eastLimitLine.length-1].latitude>d&&(d=this.eastLimitLine[this.eastLimitLine.length-1].latitude);this.westLimitLine[0].latitude>d&&(d=this.westLimitLine[0].latitude);this.westLimitLine[this.westLimitLine.length-1].latitude>d&&(d=this.westLimitLine[this.westLimitLine.length-1].latitude);if(this.northPenumbraLine){for(var g=0;g<this.northPenumbraLine.length;g++)this.northPenumbraLine[g].latitude>d&&(d=this.northPenumbraLine[g].latitude);
h(e,this.northPenumbraLine[0].longitude)&&h(k,this.northPenumbraLine[0].longitude)&&(e=this.northPenumbraLine[0].longitude);h(e,this.northPenumbraLine[this.northPenumbraLine.length-1].longitude)&&h(k,this.northPenumbraLine[this.northPenumbraLine.length-1].longitude)&&(e=this.northPenumbraLine[this.northPenumbraLine.length-1].longitude);h(c,this.northPenumbraLine[0].longitude)||h(k,this.northPenumbraLine[0].longitude)||(c=this.northPenumbraLine[0].longitude);h(c,this.northPenumbraLine[this.northPenumbraLine.length-
1].longitude)||h(k,this.northPenumbraLine[this.northPenumbraLine.length-1].longitude)||(c=this.northPenumbraLine[this.northPenumbraLine.length-1].longitude)}d+=1;90<d&&(d=89);a.setNorthLimit(d);this.eastLimitLine[0].latitude<b&&(b=this.eastLimitLine[0].latitude);this.eastLimitLine[this.eastLimitLine.length-1].latitude<b&&(b=this.eastLimitLine[this.eastLimitLine.length-1].latitude);this.westLimitLine[0].latitude<b&&(b=this.westLimitLine[0].latitude);this.westLimitLine[this.westLimitLine.length-1].latitude<
b&&(b=this.westLimitLine[this.westLimitLine.length-1].latitude);if(this.southPenumbraLine){for(g=0;g<this.southPenumbraLine.length;g++)this.southPenumbraLine[g].latitude<b&&(b=this.southPenumbraLine[g].latitude);h(e,this.southPenumbraLine[0].longitude)&&h(k,this.southPenumbraLine[0].longitudev)&&(e=this.southPenumbraLine[0].longitude);h(e,this.southPenumbraLine[this.southPenumbraLine.length-1].longitude)&&h(k,this.southPenumbraLine[this.southPenumbraLine.length-1].longitude)&&(e=this.southPenumbraLine[this.southPenumbraLine.length-
1].longitude);h(c,this.southPenumbraLine[0].longitude)||h(k,this.southPenumbraLine[0].longitude)||(c=this.southPenumbraLine[0].longitude);h(c,this.southPenumbraLine[this.southPenumbraLine.length-1].longitude)||h(k,this.southPenumbraLine[this.southPenumbraLine.length-1].longitude)||(c=this.southPenumbraLine[this.southPenumbraLine.length-1].longitude)}--b;-90>b&&(b=-89);a.setSouthLimit(b);for(g=0;g<this.westLimitLine.length-1;g++)h(e,this.westLimitLine[g].longitude)&&h(k,this.westLimitLine[g].longitude)&&
(e=this.westLimitLine[g].longitude);e=r(e,-1);a.setWestLimit(e);for(g=0;g<this.eastLimitLine.length-1;g++)h(c,this.eastLimitLine[g].longitude)||h(k,this.eastLimitLine[g].longitude)||(c=this.eastLimitLine[g].longitude);c=r(c,1);a.setEastLimit(c)}return a};this.getUmbraLimits=function(a){var d=null;if(this.northUmbraLineTimes||this.southUmbraLineTimes){var d=new PositionLimits,b=null,e=null,c,k=!1,g=!1,p=0,f;if(this.centralLineTimes){for(f=0;f<this.centralLineTimes.length;f++)if((c=this.centralLineTimes[f].getMidDate())&&
c>=a){f=this.calculateLocalCircumstances(this.centralLine[f].latitude,this.centralLine[f].longitude,0);p=f.c2c3TimeSpan.getRawMilliSeconds();break}0===p&&(f=this.calculateLocalCircumstances(this.midEclipsePoint.latitude,this.midEclipsePoint.longitude,0),p=f.c2c3TimeSpan.getRawMilliSeconds())}0===p&&(p=751E3);var l=a-p/2/864E5,p=a+p/2/864E5;if(this.northUmbraLineTimes){var n=-89;for(f=0;f<this.northUmbraLineTimes.length;f++)if(c=this.northUmbraLineTimes[f].getMidDate())if(c>=l&&!k)k=!0,null===b?b=
this.northUmbraLine[f].longitude:h(b,this.northUmbraLine[f].longitude)||(b=this.northUmbraLine[f].longitude),n<this.northUmbraLine[f].latitude&&(n=this.northUmbraLine[f].latitude),0<f&&(null===e?e=this.northUmbraLine[f-1].longitude:h(e,this.northUmbraLine[f-1].longitude)&&(e=this.northUmbraLine[f-1].longitude),n<this.northUmbraLine[f-1].latitude&&(n=this.northUmbraLine[f-1].latitude));else if(c>=p){null===b?b=this.northUmbraLine[f].longitude:h(b,this.northUmbraLine[f].longitude)||(b=this.northUmbraLine[f].longitude);
n<this.northUmbraLine[f].latitude&&(n=this.northUmbraLine[f].latitude);0<f&&(null===e?e=this.northUmbraLine[f-1].longitude:h(e,this.northUmbraLine[f-1].longitude)&&(e=this.northUmbraLine[f-1].longitude),n<this.northUmbraLine[f-1].latitude&&(n=this.northUmbraLine[f-1].latitude));g=!0;break}k&&!g&&(f--,0<f&&(null===b?b=this.northUmbraLine[f].longitude:h(b,this.northUmbraLine[f].longitude)||(b=this.northUmbraLine[f].longitude),n<this.northUmbraLine[f].latitude&&(n=this.northUmbraLine[f].latitude),0<
f&&(null===e?e=this.northUmbraLine[f-1].longitude:h(e,this.northUmbraLine[f-1].longitude)&&(e=this.northUmbraLine[f-1].longitude),n<this.northUmbraLine[f-1].latitude&&(n=this.northUmbraLine[f-1].latitude))));if(-89===n)return null;n=z(n,.05);d.setNorthLimit(n)}else d.setNorthLimit(89);if(this.southUmbraLineTimes){n=89;g=k=!1;for(f=0;f<this.southUmbraLineTimes.length;f++)if(c=this.southUmbraLineTimes[f].getMidDate())if(c>=l&&!k)k=!0,null===b?b=this.southUmbraLine[f].longitude:h(b,this.southUmbraLine[f].longitude)||
(b=this.southUmbraLine[f].longitude),n>this.southUmbraLine[f].latitude&&(n=this.southUmbraLine[f].latitude),0<f&&(null===e?e=this.southUmbraLine[f-1].longitude:h(e,this.southUmbraLine[f-1].longitude)&&(e=this.southUmbraLine[f-1].longitude),n>this.southUmbraLine[f-1].latitude&&(n=this.southUmbraLine[f-1].latitude));else if(c>=p){g=!0;null===b?b=this.southUmbraLine[f].longitude:h(b,this.southUmbraLine[f].longitude)||(b=this.southUmbraLine[f].longitude);n>this.southUmbraLine[f].latitude&&(n=this.southUmbraLine[f].latitude);
0<f&&(null===e?e=this.southUmbraLine[f-1].longitude:h(e,this.southUmbraLine[f-1].longitude)&&(e=this.southUmbraLine[f-1].longitude),n>this.southUmbraLine[f-1].latitude&&(n=this.southUmbraLine[f-1].latitude));break}k&&!g&&(f--,0<f&&(null===b?b=this.southUmbraLine[f].longitude:h(b,this.southUmbraLine[f].longitude)||(b=this.southUmbraLine[f].longitude),n>this.southUmbraLine[f].latitude&&(n=this.southUmbraLine[f].latitude),0<f&&(null===e?e=this.southUmbraLine[f-1].longitude:h(e,this.southUmbraLine[f-
1].longitude)&&(e=this.southUmbraLine[f-1].longitude),n>this.southUmbraLine[f-1].latitude&&(n=this.southUmbraLine[f-1].latitude))));if(89===n)return null;n=z(n,-.05);d.setSouthLimit(n)}else d.setSouthLimit(-89);if(this.centralLineTimes)for(k=2;4>k;k++)for(f=0;f<this.centralLineTimes.length;f++)if(2===k){if(this.centralLineTimes[f].getC2Date()&&this.centralLineTimes[f].getC2Date()>=a){null===b?b=this.centralLine[f].longitude:h(b,this.centralLine[f].longitude)||(b=this.centralLine[f].longitude);break}}else if(this.centralLineTimes[f].getC3Date()&&
this.centralLineTimes[f].getC3Date()>=a){null===e&&(e=this.centralLine[f].longitude);h(e,this.centralLine[f].longitude)&&(e=this.centralLine[f].longitude);0<f&&h(e,this.centralLine[f-1].longitude)&&(e=this.centralLine[f-1].longitude);break}b=r(b,1);d.setEastLimit(b);e=r(e,-.2);d.setWestLimit(e)}return d};this.drawPenumbraShadow=function(a){var d=null,b=this.getPenumbraLimits();if(b){var e=new SolarCalc,c=this.toDate(a),k=u(b.getEastLimit(),b.getWestLimit()),g,h=null,f=null;new ObserverCircumstances;
var d=[],l=[],k=Math.abs(k);for(g=b.getSouthLimit();g<b.getNorthLimit();g+=.5){var n=0;var m=r(b.getWestLimit(),n);var t=this.calculateLocalCircumstances(g,m,0);var v=t.circDates.getC4Date();var C=t.circDates.getC1Date();var y=e.getSolarElevation(g,m,c);var q=t.isVisible;if(!(2>y&&0<=y&&q&&null!==h&&null!==f&&h>=a&&f<=a))for(n+=3;n<=k;n+=3){m=r(b.getWestLimit(),n);t=this.calculateLocalCircumstances(g,m,0);h=t.circDates.getC4Date();f=t.circDates.getC1Date();var w=e.getSolarElevation(g,m,c);if((t=t.isVisible)||
q)if(h&&v&&(0>=y&&0<w&&h>=a&&f<=a&&(q=Math.abs(w)/(Math.abs(y)+Math.abs(w))*-3,q=r(m,q),l.push(new PositionObj(g,q))),h>=a&&v<=a&&0<=w&&(q=Math.abs(a-h)/(Math.abs(a-h)+Math.abs(a-v))*-3,q=r(m,q),l.push(new PositionObj(g,q))),h<=a&&v>=a&&0<=w&&(q=Math.abs(a-h)/(Math.abs(a-h)+Math.abs(a-v))*-3,q=r(m,q),l.push(new PositionObj(g,q)))),f&&C&&(f>=a&&C<=a&&0<=w&&(q=Math.abs(a-f)/(Math.abs(a-f)+Math.abs(a-C))*-3,q=r(m,q),d.push(new PositionObj(g,q))),f<=a&&C>=a&&0<=w&&(q=Math.abs(a-f)/(Math.abs(a-f)+Math.abs(a-
C))*-3,q=r(m,q),d.push(new PositionObj(g,q))),0<=y&&0>w&&v>=a&&C<=a)){q=Math.abs(w)/(Math.abs(y)+Math.abs(w))*-3;q=r(m,q);d.push(new PositionObj(g,q));break}v=h;C=f;y=w;q=t}}0<l.length&&(l=this.sortShadowLine(!0,l));0<d.length&&(d=this.sortShadowLine(!1,d));a=d;1<a.length&&1<l.length&&(b=a[a.length-1].longitude,e=l[l.length-1].longitude,c=l[l.length-1].latitude,(75<Math.abs(a[a.length-1].latitude)||75<Math.abs(c))&&120<u(b,e)&&(e=u(b,e)/5,c=r(b,-1*e),a.push(new PositionObj(-89.99,c)),c=r(b,-2*e),
a.push(new PositionObj(-89.99,c)),c=r(b,-3*e),a.push(new PositionObj(-89.99,c)),c=r(b,-4*e),a.push(new PositionObj(-89.99,c))));0<l.length&&(d=d.concat(l.reverse()));1<d.length&&(d=d.concat(d[0]));2>d.length&&(d=null)}return d};this.sortShadowLine=function(a,d){for(var b=d[0].longitude,e=0,c=0;c<d.length;c++)a?h(b,d[c].longitude)&&(b=d[c].longitude,e=c):h(b,d[c].longitude)||(b=d[c].longitude,e=c);b=[];c=[];b=b.concat(d.slice(0,e+1));c=c.concat(d.slice(e+1,d.length));a?(b.sort(A),c.sort(B)):(b.sort(B),
c.sort(A));return c=c.concat(b)};this.drawUmbraShadow=function(a){var d=new SolarCalc,b=this.toDate(a),e=null,c=this.getUmbraLimits(a);if(c){var k=r(0,c.getWestLimit()-c.getEastLimit()),g,h=null,f=null;new ObserverCircumstances;var e=[],l=[],k=Math.abs(k);for(g=c.getSouthLimit();g<=c.getNorthLimit();g+=.025){var n=0;var m=r(c.getWestLimit(),n);var t=this.calculateLocalCircumstances(g,m,0);var v=t.circDates.getC3Date();var u=t.circDates.getC2Date();var y=d.getSolarElevation(g,m,b);var q=t.isVisible;
if(!(2>y&&0<=y&&q&&null!==h&&null!==f&&h>=a&&f<=a))for(n+=.05;n<=k;n+=.05){m=r(c.getWestLimit(),n);t=this.calculateLocalCircumstances(g,m,0);h=t.circDates.getC3Date();f=t.circDates.getC2Date();var w=d.getSolarElevation(g,m,b);if((t=t.isVisible)||q){h&&v&&(0>=y&&0<w&&h>=a&&f<=a&&(q=Math.abs(w)/(Math.abs(y)+Math.abs(w))*-.05,q=r(m,q),l.push(new PositionObj(g,q))),h>=a&&v<=a&&0<=w&&(q=Math.abs(a-h)/(Math.abs(a-h)+Math.abs(a-v))*-.05,q=r(m,q),l.push(new PositionObj(g,q))),h<=a&&v>=a&&0<=w&&(q=Math.abs(a-
h)/(Math.abs(a-h)+Math.abs(a-v))*-.05,q=r(m,q),e.push(new PositionObj(g,q))));if(f&&u)if(f>=a&&u<=a&&0<=w)q=Math.abs(a-f)/(Math.abs(a-f)+Math.abs(a-u))*-.05,m=r(m,q),e.push(new PositionObj(g,m));else if(f<=a&&u>=a&&0<=w)q=Math.abs(a-f)/(Math.abs(a-f)+Math.abs(a-u))*-.05,m=r(m,q),l.push(new PositionObj(g,m));else if(0<=y&&0>w&&v>=a&&u<=a){q=Math.abs(w)/(Math.abs(y)+Math.abs(w))*-.05;m=r(m,q);e.push(new PositionObj(g,m));break}v=h;u=f;y=w;q=t}}}1<l.length&&(l=l.reverse(),e=e.concat(l));1<e.length&&
(e=e.concat(e[0]));2>e.length&&(e=null)}return e};this.getJulianDay=function(a){a=a.t+this.besselianElements.t0-(this.besselianElements.dUTC-.05)/3600;0>a&&(a+=24);24<=a&&(a-=24);return this.besselianElements.julianDayMax-a/24};this.getAlt=function(a){return 180*a.alt/Math.PI};this.getAzi=function(a){a=180*a.azi/Math.PI;0>a&&(a+=360);360<=a&&(a-=360);return a};this.getP=function(a){a=180*a.p/Math.PI;0>a&&(a+=360);360<=a&&(a-=360);return a};this.getDate=function(a){return isNaN(a.t)||isNaN(this.besselianElements.t0)||
isNaN(this.besselianElements.dUTC)?null:(a=a.t+this.besselianElements.t0-this.besselianElements.dUTC/3600,0>a&&(a+=24),24<=a&&(a-=24),Math.floor(this.besselianElements.julianDayMax-a/24+1538)+a/24)};this.getAll=function(){this.getMid();this.observational(this.midCircumstances);this.midCircumstances.mid=Math.sqrt(this.midCircumstances.u*this.midCircumstances.u+this.midCircumstances.vLoc*this.midCircumstances.vLoc);this.midCircumstances.magnitude=(this.midCircumstances.l1prime-this.midCircumstances.mid)/
(this.midCircumstances.l1prime+this.midCircumstances.l2prime);this.midCircumstances.moonSun=(this.midCircumstances.l1prime-this.midCircumstances.l2prime)/(this.midCircumstances.l1prime+this.midCircumstances.l2prime);this.getC1C4();this.observational(this.c1Circumstances);this.observational(this.c4Circumstances);this.getC2C3();this.observational(this.c2Circumstances);this.observational(this.c3Circumstances);0<this.midCircumstances.magnitude?this.midCircumstances.mid<this.midCircumstances.l2prime||
this.midCircumstances.mid<-this.midCircumstances.l2prime?(this.midCircumstances.localType=0>this.midCircumstances.l2prime?3:2,this.c2Circumstances.mid=999.9,this.c3Circumstances.mid=999.9):this.midCircumstances.localType=1:this.midCircumstances.localType=0};this.getCoverage=function(){if(0>=this.midCircumstances.magnitude)return 0;if(1<=this.midCircumstances.magnitude)return 100;if(2===this.midCircumstances.localType)var a=this.midCircumstances.moonSun*this.midCircumstances.moonSun;else{a=Math.acos((this.midCircumstances.l1prime*
this.midCircumstances.l1prime+this.midCircumstances.l2prime*this.midCircumstances.l2prime-2*this.midCircumstances.mid*this.midCircumstances.mid)/(this.midCircumstances.l1prime*this.midCircumstances.l1prime-this.midCircumstances.l2prime*this.midCircumstances.l2prime));var d=Math.acos((this.midCircumstances.l1prime*this.midCircumstances.l2prime+this.midCircumstances.mid*this.midCircumstances.mid)/this.midCircumstances.mid/(this.midCircumstances.l1prime+this.midCircumstances.l2prime));var b=Math.PI-
d-a;a=(this.midCircumstances.moonSun*this.midCircumstances.moonSun*b+d-this.midCircumstances.moonSun*Math.sin(a))/Math.PI}return a?(1E3*a+.5)/10:0};this.getDepth=function(){var a=Math.abs(this.midCircumstances.mid/this.midCircumstances.l2prime);return 100*(0>a?1+a:1-a)};this.getMid=function(){var a=0,d=1;this.midCircumstances.eventType=0;this.midCircumstances.t=0;for(this.timeLocalDependent(this.midCircumstances);(1E-6<d||-1E-6>d)&&a<CALC_ITERATIONS;)d=(this.midCircumstances.u*this.midCircumstances.a+
this.midCircumstances.vLoc*this.midCircumstances.b)/this.midCircumstances.nSquared,this.midCircumstances.t-=d,a++,this.timeLocalDependent(this.midCircumstances)};this.getC1C4=function(){var a=Math.sqrt(this.midCircumstances.nSquared);var d=this.midCircumstances.a*this.midCircumstances.vLoc-this.midCircumstances.u*this.midCircumstances.b;d=d/a/this.midCircumstances.l1prime;d=Math.sqrt(1-d*d)*this.midCircumstances.l1prime/a;this.c1Circumstances.eventType=-2;this.c4Circumstances.eventType=2;this.c1Circumstances.t=
this.midCircumstances.t-d;this.c4Circumstances.t=this.midCircumstances.t+d;this.c1c4Iterate(this.c1Circumstances);this.c1c4Iterate(this.c4Circumstances)};this.c1c4Iterate=function(a){var d;this.timeLocalDependent(a);var b=0>a.eventType?-1:1;var e=1;for(d=0;(1E-6<e||-1E-6>e)&&d<CALC_ITERATIONS;){var c=Math.sqrt(a.nSquared);e=a.a*a.vLoc-a.u*a.b;e=e/c/a.l1prime;e=b*Math.sqrt(1-e*e)*a.l1prime/c;e=(a.u*a.a+a.vLoc*a.b)/a.nSquared-e;a.t-=e;this.timeLocalDependent(a);d++}return a};this.getC2C3=function(){var a=
Math.sqrt(this.midCircumstances.nSquared);var d=this.midCircumstances.a*this.midCircumstances.vLoc-this.midCircumstances.u*this.midCircumstances.b;d=d/a/this.midCircumstances.l2prime;d=Math.sqrt(1-d*d)*this.midCircumstances.l2prime/a;this.c2Circumstances.eventType=-1;this.c3Circumstances.eventType=1;0>this.midCircumstances.l2prime?(this.c2Circumstances.t=this.midCircumstances.t+d,this.c3Circumstances.t=this.midCircumstances.t-d):(this.c2Circumstances.t=this.midCircumstances.t-d,this.c3Circumstances.t=
this.midCircumstances.t+d);this.c2c3Iterate(this.c2Circumstances);this.c2c3Iterate(this.c3Circumstances)};this.c2c3Iterate=function(a){var d;this.timeLocalDependent(a);var b=0>a.eventType?-1:1;0>this.midCircumstances.l2prime&&(b=-b);var e=1;for(d=0;(1E-6<e||-1E-6>e)&&50>d;){var c=Math.sqrt(a.nSquared);e=a.a*a.vLoc-a.u*a.b;e=e/c/a.l2prime;e=b*Math.sqrt(1-e*e)*a.l2prime/c;e=(a.u*a.a+a.vLoc*a.b)/a.nSquared-e;a.t-=e;this.timeLocalDependent(a);d++}return a};this.timeLocalDependent=function(a){this.timeDependent(a);
a.h=a.mu-this.observerConstants.getLongRadians()-this.besselianElements.dT/13713.44;a.sinH=Math.sin(a.h);a.cosH=Math.cos(a.h);a.xi=this.observerConstants.getRhoCosO()*a.sinH;a.eta=this.observerConstants.getRhoSinO()*a.cosDelta-this.observerConstants.getRhoCosO()*a.cosH*a.sinDelta;a.zeta=this.observerConstants.getRhoSinO()*a.sinDelta+this.observerConstants.getRhoCosO()*a.cosH*a.cosDelta;a.dxi=a.dmu*this.observerConstants.getRhoCosO()*a.cosH;a.deta=a.dmu*a.xi*a.sinDelta-a.zeta*a.dd;a.u=a.x-a.xi;a.vLoc=
a.y-a.eta;a.a=a.dx-a.dxi;a.b=a.dy-a.deta;var d=a.eventType;if(-2===d||0===d||2===d)a.l1prime=a.l1-a.zeta*this.besselianElements.tanF1;if(-1===d||0===d||1===d)a.l2prime=a.l2-a.zeta*this.besselianElements.tanF2;a.nSquared=a.a*a.a+a.b*a.b;return a};this.timeDependent=function(a){var d=a.t;var b=this.besselianElements.x3*d+this.besselianElements.x2;b=b*d+this.besselianElements.x1;b=b*d+this.besselianElements.x0;a.x=b;b=3*this.besselianElements.x3*d+2*this.besselianElements.x2;b=b*d+this.besselianElements.x1;
a.dx=b;b=this.besselianElements.y3*d+this.besselianElements.y2;b=b*d+this.besselianElements.y1;b=b*d+this.besselianElements.y0;a.y=b;b=3*this.besselianElements.y3*d+2*this.besselianElements.y2;b=b*d+this.besselianElements.y1;a.dy=b;b=this.besselianElements.d2*d+this.besselianElements.d1;b=b*d+this.besselianElements.d0;b=b*Math.PI/180;a.d=b;a.sinDelta=Math.sin(b);a.cosDelta=Math.cos(b);b=2*this.besselianElements.d2*d+this.besselianElements.d1;b=b*Math.PI/180;a.dd=b;b=this.besselianElements.m2*d+this.besselianElements.m1;
b=b*d+this.besselianElements.m0;360<=b&&(b-=360);b=b*Math.PI/180;a.mu=b;b=2*this.besselianElements.m2*d+this.besselianElements.m1;b=b*Math.PI/180;a.dmu=b;var e=a.eventType;if(-2===e||0===e||2===e)b=this.besselianElements.l12*d+this.besselianElements.l11,b=b*d+this.besselianElements.l10,a.l1=b,a.dl1=2*this.besselianElements.l12*d+this.besselianElements.l11;if(-1===e||0===e||1===e)b=this.besselianElements.l22*d+this.besselianElements.l21,b=b*d+this.besselianElements.l20,a.l2=b,a.dl2=2*this.besselianElements.l22*
d+this.besselianElements.l21;return a};this.observational=function(a){var d=0===a.eventType?1:3!==this.midCircumstances.localType||-1!==a.eventType&&1!==a.eventType?1:-1;a.p=Math.atan2(d*a.u,d*a.vLoc);var b=Math.sin(this.observerConstants.getLatRadians());d=Math.cos(this.observerConstants.getLatRadians());a.alt=Math.asin(a.sinDelta*b+a.cosDelta*d*a.cosH);a.q=Math.asin(d*a.sinH/Math.cos(a.alt));0>a.eta&&(a.q=Math.PI-a.q);a.vObs=a.p-a.q;a.azi=Math.atan2(-1*a.sinH*a.cosDelta,a.sinDelta*d-a.cosH*b*a.cosDelta)};
this.setMaxJulianDay=function(a){this.besselianElements.julianDayMax=a;this.maxEclipseDate=julianDayToTime(this.besselianElements.julianDayMax)};this.getMaxEclipseDate=function(){return this.maxEclipseDate};this.getMaxEclipseDateJD=function(){return this.besselianElements.julianDayMax};this.isTotalOrAnnular=function(){return"Annular"===this.type||"Total"===this.type||"Hybrid"===this.type?!0:!1};this.set(l)}
var Eclipses=function(l){function k(){a=!0;console.log("Eclipse load error called.");"function"===typeof B&&B()}function u(a,b){var d=new XMLHttpRequest;d.open("GET",a,!0);d.onload=function(a){if(200===d.status)b(d.response);else{if(0===d.status){if("undefined"!==typeof d.response&&""!==d.response){b(d.response);return}console.log("Empty eclipse load response.")}else console.log("Eclipse load XHR status error: "+d.status);k()}};d.onerror=function(a){console.log("Other request error.");k()};d.send()}
function r(){h.sort(function(a,b){return a.maxEclipseDate.getTime()-b.maxEclipseDate.getTime()})}function z(d){console.log("Loading cat");d=d.match(/[^\r\n]+/g);var b=0;if(0===h.length)console.log("No eclipse loaded from catalog."),k();else{for(var e=0;e<h.length;e++)for(;b<d.length;b++)if(d[b].length===VALID_LINE_LENGTH){var c=d[b].substr(DATE_START_IDX,DATE_STRING_LENGTH);var l=c.substr(0,4);var g=c.substr(5,6);c=c.substr(13,9);l=new Date(g+", "+l+" "+c+" GMT");if(isNaN(l.getTime()))console.log("Unable to parse date catalog line: "+
b);else if("-"===d[b][DATE_START_IDX]&&l.setUTCFullYear(-1*l.getUTCFullYear()),g=l,c=h[e].maxEclipseDate,l=6E4,isNaN(void 0)||(l=void 0),isNaN(g.getTime())?l=!1:isNaN(c.getTime())?l=!1:(g=g.getTime()-c.getTime(),l=g<=l&&g>=-1*l?!0:!1),l){l=d[b];g=e;if(0<=g&&g<h.length){var c=parseFloat(l.substr(LAT_START_IDX,LAT_LENGTH)),p=parseFloat(l.substr(LONG_START_IDX,LONG_LENGTH));"S"===l[LAT_START_IDX+LAT_LENGTH]&&(c*=-1);"W"===l[LONG_START_IDX+LONG_LENGTH]&&(p*=-1);h[g].midEclipsePoint.setPosition(c,p)}l=
d[b];g=e;if(0<=g&&g<h.length)switch(l[ECLIPSE_TYPE_IDX]){case "P":h[g].type="Partial";break;case "A":h[g].type="Annular";break;case "T":h[g].type="Total";break;case "H":h[g].type="Hybrid";break;default:console.log("No eclipse type found.")}break}}console.log("Load complete, TODO: remove data responded.");a||(console.log("Load complete called."),"function"===typeof A&&A())}}var h=[],A=null,B=null,a=!1;this.loadEclipseElements=function(a,b,e,c){A=e;B=c;importScripts(b);console.log("Loading Besselian elements.");
b=SE1901();if(b=b.concat(SE2001())){for(c=0;c<b.length-27;c++)e=new EclipseData,e.setMaxJulianDay(Number(b[c])),c++,e.besselianElements.t0=Number(b[c]),c++,e.besselianElements.tMin=Number(b[c]),c++,e.besselianElements.tMax=Number(b[c]),c++,e.besselianElements.dUTC=Number(b[c]),c++,e.besselianElements.dT=Number(b[c]),c++,e.besselianElements.x0=Number(b[c]),c++,e.besselianElements.x1=Number(b[c]),c++,e.besselianElements.x2=Number(b[c]),c++,e.besselianElements.x3=Number(b[c]),c++,e.besselianElements.y0=
Number(b[c]),c++,e.besselianElements.y1=Number(b[c]),c++,e.besselianElements.y2=Number(b[c]),c++,e.besselianElements.y3=Number(b[c]),c++,e.besselianElements.d0=Number(b[c]),c++,e.besselianElements.d1=Number(b[c]),c++,e.besselianElements.d2=Number(b[c]),c++,e.besselianElements.m0=Number(b[c]),c++,e.besselianElements.m1=Number(b[c]),c++,e.besselianElements.m2=Number(b[c]),c++,e.besselianElements.l10=Number(b[c]),c++,e.besselianElements.l11=Number(b[c]),c++,e.besselianElements.l12=Number(b[c]),c++,e.besselianElements.l20=
Number(b[c]),c++,e.besselianElements.l21=Number(b[c]),c++,e.besselianElements.l22=Number(b[c]),c++,e.besselianElements.tanF1=Number(b[c]),c++,e.besselianElements.tanF2=Number(b[c]),h.push(e);b.length=0;r();b=!0}else console.log("No eclipse elements found in javascript file."),b=!1;b?u(a,z):k()};this.deleteEclipses=function(){h.length=0};this.addEclipse=function(a){h.push(new EclipseData(a))};this.getEclipse=function(a){return!isNaN(a)&&a<this.getEclipseCount()?h[a]:null};this.getEclipseCount=function(){return h.length};
this.getNextEclipseIdx=function(){var a=new Date;a.setUTCDate(a.getUTCDate()-2);for(var b=0;b<this.getEclipseCount()&&!(a<h[b].maxEclipseDate);b++);b>=this.getEclipseCount()&&(b=this.getEclipseCount()-1,0>b&&(b=0));return b};this.getNextEclipse=function(){return h[this.getNextEclipseIdx()]};this.eclipseToJSON=function(){return JSON.stringify(h)};this.copyEclipsesIn=function(a){if("undefined"!==typeof a&&Array.isArray(a))for(var b=0;b<a.length;b++)this.addEclipse(a[b])};this.copyEclipsesIn(l)};